project_id = "ygdbjyhtlzdkwhczvfpb"

[functions.train-lora]
enabled = true
verify_jwt = true
import_map = "./functions/train-lora/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/train-lora/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/train-lora/*.html" ]

[functions.training-webhook-handler]
enabled = true
verify_jwt = true
import_map = "./functions/training-webhook-handler/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/training-webhook-handler/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/training-webhook-handler/*.html" ]
